version: "3.8"

services:
  app:
    build: .
    container_name: express-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always

  mongo:
    image: mongo:7
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
